// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: finding.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FindingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FindingRequest) Reset() {
	*x = FindingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingRequest) ProtoMessage() {}

func (x *FindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingRequest.ProtoReflect.Descriptor instead.
func (*FindingRequest) Descriptor() ([]byte, []int) {
	return file_finding_proto_rawDescGZIP(), []int{0}
}

func (x *FindingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FindingResponse) Reset() {
	*x = FindingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingResponse) ProtoMessage() {}

func (x *FindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingResponse.ProtoReflect.Descriptor instead.
func (*FindingResponse) Descriptor() ([]byte, []int) {
	return file_finding_proto_rawDescGZIP(), []int{1}
}

func (x *FindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_finding_proto protoreflect.FileDescriptor

var file_finding_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x0f,
	0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x52, 0x0a, 0x0e, 0x46, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0d, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_finding_proto_rawDescOnce sync.Once
	file_finding_proto_rawDescData = file_finding_proto_rawDesc
)

func file_finding_proto_rawDescGZIP() []byte {
	file_finding_proto_rawDescOnce.Do(func() {
		file_finding_proto_rawDescData = protoimpl.X.CompressGZIP(file_finding_proto_rawDescData)
	})
	return file_finding_proto_rawDescData
}

var file_finding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_finding_proto_goTypes = []interface{}{
	(*FindingRequest)(nil),  // 0: proto.FindingRequest
	(*FindingResponse)(nil), // 1: proto.FindingResponse
}
var file_finding_proto_depIdxs = []int32{
	0, // 0: proto.FindingService.ReportMissing:input_type -> proto.FindingRequest
	1, // 1: proto.FindingService.ReportMissing:output_type -> proto.FindingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_finding_proto_init() }
func file_finding_proto_init() {
	if File_finding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finding_proto_goTypes,
		DependencyIndexes: file_finding_proto_depIdxs,
		MessageInfos:      file_finding_proto_msgTypes,
	}.Build()
	File_finding_proto = out.File
	file_finding_proto_rawDesc = nil
	file_finding_proto_goTypes = nil
	file_finding_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FindingServiceClient is the client API for FindingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FindingServiceClient interface {
	ReportMissing(ctx context.Context, in *FindingRequest, opts ...grpc.CallOption) (*FindingResponse, error)
}

type findingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFindingServiceClient(cc grpc.ClientConnInterface) FindingServiceClient {
	return &findingServiceClient{cc}
}

func (c *findingServiceClient) ReportMissing(ctx context.Context, in *FindingRequest, opts ...grpc.CallOption) (*FindingResponse, error) {
	out := new(FindingResponse)
	err := c.cc.Invoke(ctx, "/proto.FindingService/ReportMissing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindingServiceServer is the server API for FindingService service.
type FindingServiceServer interface {
	ReportMissing(context.Context, *FindingRequest) (*FindingResponse, error)
}

// UnimplementedFindingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFindingServiceServer struct {
}

func (*UnimplementedFindingServiceServer) ReportMissing(context.Context, *FindingRequest) (*FindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMissing not implemented")
}

func RegisterFindingServiceServer(s *grpc.Server, srv FindingServiceServer) {
	s.RegisterService(&_FindingService_serviceDesc, srv)
}

func _FindingService_ReportMissing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindingServiceServer).ReportMissing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FindingService/ReportMissing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindingServiceServer).ReportMissing(ctx, req.(*FindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FindingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FindingService",
	HandlerType: (*FindingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportMissing",
			Handler:    _FindingService_ReportMissing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finding.proto",
}
